// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBigRwISZNO_yk4DlYUXcddgGQbcLvrnoQ',
    appId: '1:584426808860:web:d7fca7de37456dbeb961d9',
    messagingSenderId: '584426808860',
    projectId: 'my-otp-login-app-aditya-6467d',
    authDomain: 'my-otp-login-app-aditya-6467d.firebaseapp.com',
    storageBucket: 'my-otp-login-app-aditya-6467d.firebasestorage.app',
    measurementId: 'G-7307VG7Q2W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCjd-AXp4QI4vp5-H6Bs8YzuT68Vi38Hg',
    appId: '1:584426808860:android:7834917311ac7805b961d9',
    messagingSenderId: '584426808860',
    projectId: 'my-otp-login-app-aditya-6467d',
    storageBucket: 'my-otp-login-app-aditya-6467d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBivZxrfqYgihMmLLf9gKTJT3yr13WaFRc',
    appId: '1:584426808860:ios:c453bf13f600e9cab961d9',
    messagingSenderId: '584426808860',
    projectId: 'my-otp-login-app-aditya-6467d',
    storageBucket: 'my-otp-login-app-aditya-6467d.firebasestorage.app',
    iosBundleId: 'com.example.qisTech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBivZxrfqYgihMmLLf9gKTJT3yr13WaFRc',
    appId: '1:584426808860:ios:c453bf13f600e9cab961d9',
    messagingSenderId: '584426808860',
    projectId: 'my-otp-login-app-aditya-6467d',
    storageBucket: 'my-otp-login-app-aditya-6467d.firebasestorage.app',
    iosBundleId: 'com.example.qisTech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBigRwISZNO_yk4DlYUXcddgGQbcLvrnoQ',
    appId: '1:584426808860:web:5bd5e20ac6557614b961d9',
    messagingSenderId: '584426808860',
    projectId: 'my-otp-login-app-aditya-6467d',
    authDomain: 'my-otp-login-app-aditya-6467d.firebaseapp.com',
    storageBucket: 'my-otp-login-app-aditya-6467d.firebasestorage.app',
    measurementId: 'G-0DK6RTCCSF',
  );

}